base_dev_dir: '/share/portal/pd337'
# base_dev_dir: '/share/portal/kk837'

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/label_sim_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

resize_shape: [124,124]
data_path: ${base_dev_dir}/xskill/datasets/kitchen_dataset
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/no_pairing_twohands_2024-05-28_21-11-55'
exp_path: '${base_dev_dir}/xskill/experiment/pretrain/orig_batch'
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/NO_PAIRING_SINGLEHAND'
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/TWOHAND_75_pairing_twohands_segments_2024-06-04_01-52-08'
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/TWOHAND_100_pairing_twohands_segments_2024-06-04_01-52-02'

# ckpt: 40
ckpt: 79
# ckpt: 27
# ckpt: 40

# human_type: 'human'
# human_type: 'singlehand'
human_type: 'human'
device: 'cuda:0'
plot_top_k: null
verbose: True
eps_num: 0
save_path: human.png
batch_size: 28