base_dev_dir: ''

hydra:
  run:
    dir: '${base_dev_dir}/rhyme/experiment/label_sim_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

resize_shape: [124,124]
data_path: ${base_dev_dir}/rhyme/datasets/kitchen_dataset
pretrain_model_name: ''
exp_path: '${base_dev_dir}/rhyme/experiment/pretrain/${pretrain_model_name}'
ckpt: 40
device: 'cuda:0'
plot_top_k: null
verbose: True

use_huggingface: true
dataset_name: "prithwishdan/RHyME"
split: "train"
cross_embodiment: ''
include_robot: True




batch_size: 28